# Generated by Django 5.2.7 on 2026-06-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_remove_product_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_media_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='media_url',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
