# Generated by Django 5.2.7 on 2026-06-01 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_instagramaccount_reconnect_required'),
        ('products', '0003_alter_product_main_media_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='instagram_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='accounts.instagramaccount'),
        ),
    ]
