# Generated by Django 5.2.7 on 2026-06-03 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_instagramaccount_id_alter_user_id'),
        ('products', '0006_category_user_alter_category_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_id', models.CharField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_pic_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAID', 'Paid'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=20)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instagram_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.instagramaccount')),
                ('instagram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.instagramuser')),
            ],
        ),
        migrations.CreateModel(
            name='ConversationProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('source_type', models.CharField(choices=[('DM', 'DM'), ('COMMENT', 'Comment'), ('STORY', 'Story Reply'), ('HASHTAG', 'Hashtag'), ('MANUAL', 'Manual')], default='DM', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_products', to='products.conversation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_conversations', to='products.product')),
            ],
        ),
    ]
