# Generated by Django 5.2.7 on 2026-06-03 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_instagramuser_conversation_conversationproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='instagram_account',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='instagram_user',
        ),
        migrations.RemoveField(
            model_name='conversationproduct',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='conversationproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='InstagramUser',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='ConversationProduct',
        ),
    ]
