# Generated by Django 5.2.7 on 2026-06-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_conversation_instagram_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='media_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
