# Generated by Django 5.2.7 on 2026-05-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_instagramaccount_instagram_scoped_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramaccount',
            name='reconnect_required',
            field=models.BooleanField(default=False),
        ),
    ]
