# Generated by Django 5.2.7 on 2026-06-01 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_instagramaccount_reconnect_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramaccount',
            name='reconnect_required',
        ),
    ]
