# Generated by Django 6.0.4 on 2026-06-06 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_instagramaccount_id_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(blank=True, max_length=255, null=True)),
                ('store_logo', models.URLField(blank=True, max_length=2000, null=True)),
                ('show_related_products', models.BooleanField(default=True)),
                ('enable_instagram_button', models.BooleanField(default=True)),
                ('enable_whatsapp_button', models.BooleanField(default=True)),
                ('template_id', models.CharField(default='glass_monochrome', max_length=100)),
                ('theme_id', models.CharField(default='dark', max_length=100)),
                ('custom_colors', models.JSONField(blank=True, default=dict)),
                ('custom_fonts', models.JSONField(blank=True, default=dict)),
                ('custom_settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instagram_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='website_settings', to='accounts.instagramaccount')),
            ],
        ),
    ]
