# Generated by Django 5.2.7 on 2026-06-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_websitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramaccount',
            name='profile_picture_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
