# Generated by Django 5.2.7 on 2026-05-07 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='instagramaccount',
            old_name='created_at',
            new_name='connected_at',
        ),
        migrations.RenameField(
            model_name='instagramaccount',
            old_name='instagram_id',
            new_name='instagram_user_id',
        ),
        migrations.RemoveField(
            model_name='instagramaccount',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='instagramaccount',
            name='user',
        ),
        migrations.AddField(
            model_name='instagramaccount',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_uid', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('login_methods', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active_instagram_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_user', to='accounts.instagramaccount')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='instagramaccount',
            name='app_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='instagram_accounts', to='accounts.appuser'),
            preserve_default=False,
        ),
    ]
