# Generated by Django 5.2.7 on 2026-05-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramaccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='instagramaccount',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
