# Generated by Django 5.2.7 on 2026-05-13 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_instagramaccount_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramaccount',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instagram_accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
