# Generated by Django 5.2.7 on 2026-05-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_instagramaccount_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramaccount',
            name='instagram_scoped_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='instagramaccount',
            name='instagram_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
