# Generated by Django 5.2.7 on 2026-06-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_enquiry_media_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_business_follow_user',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
