# Generated by Django 5.2.7 on 2026-06-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_customer_is_business_follow_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinteraction',
            name='media_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
