# Generated by Django 5.2.7 on 2026-06-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_customerinteraction_media_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinteraction',
            name='content_type',
            field=models.CharField(blank=True, choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('FILE', 'File'), ('REEL', 'Instagram Reel'), ('POST', 'Instagram Post'), ('STORY', 'Instagram Story'), ('CAROUSEL', 'Instagram Carousel')], max_length=30, null=True),
        ),
    ]
