# Generated by Django 5.2.7 on 2026-06-11 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_customerinteraction_content_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerinteraction',
            old_name='content_type',
            new_name='message_type',
        ),
    ]
