# Generated by Django 5.2.7 on 2026-06-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_rename_content_type_customerinteraction_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinteraction',
            name='render_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerinteraction',
            name='message_type',
            field=models.CharField(blank=True, choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('FILE', 'File'), ('QUICK_REPLY', 'Quick Reply'), ('BUTTON_TEMPLATE', 'Button Template'), ('GENERIC_TEMPLATE', 'Generic Template'), ('REEL', 'Instagram Reel'), ('POST', 'Instagram Post'), ('STORY', 'Instagram Story'), ('CAROUSEL', 'Instagram Carousel')], max_length=30, null=True),
        ),
    ]
