# Generated by Django 5.2.7 on 2026-06-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_customerinteraction_render_payload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinteraction',
            name='message_source',
            field=models.CharField(choices=[('WEBIU', 'Web UI'), ('AI', 'AI Assistant'), ('AUTOMATION', 'Workflow Automation'), ('IGSYSTEM', 'IG System')], default='CUSTOMER', max_length=20),
        ),
    ]
