# Generated by Django 5.2.7 on 2026-06-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_customerinteraction_message_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinteraction',
            name='message_source',
            field=models.CharField(choices=[('WEBIU', 'Web UI'), ('AI', 'AI Assistant'), ('AUTOMATION', 'Workflow Automation'), ('IGSYSTEM', 'IG System')], default='IGSYSTEM', max_length=20),
        ),
    ]
