# Generated by Django 5.2.7 on 2026-06-01 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_published',
        ),
        migrations.AddField(
            model_name='product',
            name='cloudinary_metadata',
            field=models.JSONField(blank=True, help_text='Metadata stored when uploading to Cloudinary', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(default='KWD', max_length=3),
        ),
        migrations.AddField(
            model_name='product',
            name='instagram_permalink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('SOLD', 'Sold'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='cloudinary_metadata',
            field=models.JSONField(blank=True, help_text='Metadata stored when uploading to Cloudinary', null=True),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='source_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('seller', 'source_id'), name='unique_source_per_seller'),
        ),
    ]
