# Generated by Django 5.2.7 on 2026-05-07 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='media_url',
            new_name='main_media_url',
        ),
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=False, help_text='True if converted to a sellable product'),
        ),
        migrations.AddField(
            model_name='product',
            name='source_id',
            field=models.CharField(blank=True, help_text='Instagram shortcode or external ID', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='source_type',
            field=models.CharField(choices=[('REEL', 'Instagram Reel'), ('POST', 'Instagram Post'), ('MANUAL', 'Manual Creation')], default='MANUAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_negotiable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_url', models.URLField(max_length=500)),
                ('media_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video')], max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='products.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='InstagramProductMapping',
        ),
    ]
