# Generated by Django 5.2.7 on 2026-06-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_instagram_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Dynamic key-value specifications for the product.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original price before any discounts or offers.', max_digits=10, null=True),
        ),
    ]
